version: '3'

services:
###> symfony/mailer ###
  mailer:
    image: sj26/mailcatcher
    ports: ["1025", "1080"]
###< symfony/mailer ###

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###
